# This workflow has been replaced by daily-sync.yml
# Keeping this file for reference only - it will not run

name: "[DISABLED] Old Monday.com Sync - DO NOT USE"

# Workflow is disabled by removing all triggers
on:
  # No triggers defined - this workflow will never run automatically
  workflow_dispatch:
    inputs:
      note:
        description: 'This workflow is disabled. Use "Daily Monday.com Task Sync" instead.'
        required: false

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Disabled
        run: |
          echo "❌ This workflow has been disabled and replaced."
          echo ""
          echo "✅ Please use: 'Daily Monday.com Task Sync' workflow instead"
          echo ""
          echo "The new workflow:"
          echo "  - Triggers the Render service via /trigger endpoint"
          echo "  - Runs at 9 AM EST weekdays"
          echo "  - Does not require secrets in GitHub Actions"
          echo "  - More reliable and simpler"
          exit 1
