name: Monday.com to Slack Task Sync
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
    inputs:
      test_user_only:
        description: 'Test with single user (Connor)'
        required: false
        type: boolean
        default: false
jobs:
  sync-tasks:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run automation
        env:
          MONDAY_API_KEY: ${{ secrets.MONDAY_API_KEY }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          TEST_MODE: ${{ github.event.inputs.test_user_only || 'false' }}
        run: node src/automation.js
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: automation-logs-${{ github.run_number }}
          path: logs/
          retention-days: 7
